#!/bin/bash

printf 'gathering walmart data...\n'
cd services/
python walmart_api_recorder.py

printf 'gathering amazon data...\n'
cd scrapers/
scrapy crawl amazon_spider

printf 'gathering costco_data...\n'
scrapy crawl costco_spider

printf 'collected data\n'
